### ISSUE TITLE
aggregateId não é obrigatório e validação quebra o programa

### ISSUE THREAD

**Issue by filipegar** [luisdalmolin/laravel-zenvia-channel#5]
@luisdalmolin acho que essa alteração para contemplar o aggregateId prejudicou o funcionamento do channel.

Posso enviar um pull com a remoção das linhas abaixo? 
https://github.com/luisdalmolin/laravel-zenvia-channel/blob/516659fb363d3045769e79a0e408e91769f20605/src/Zenvia.php#L80-L82

Esse parâmetro é totalmente opcional e o codigo de versoes antigas ainda funciona. https://imgur.com/a/2lwRgQ8

Eu vejo o aggregateId como um parâmetro da mensagem e não do channel. Acredito que a mudança teria de ser maior para colocar o mesmo comportamento da documentação da zenvia.

**Comment by luisdalmolin** [comment]
Opa @filipegar

Pode enviar sim, não sabia que isso era uma breaking change e que isso era opcional. Foi mal. 
Como não estou mais usando o serviço não consegui testar realmente.

Mas assim que tu enviar faço o merge e crio a nova versão.
