### ISSUE TITLE
Usage not clear

### ISSUE THREAD

**Issue by Ludplay** [luisdalmolin/laravel-zenvia-channel#7]
Hey, @luisdalmolin. Great job, but I think it's a little bit confusing this usage. We don't know if we create a provider or if we call zenvia direct in our controller.

It would be interesting if you could perform an example calling the method so we could know the idea about the way we are supposed to use it.

**Comment by luisdalmolin** [comment]
@Ludplay This is an adapter for using it with Laravel Notifications (https://laravel.com/docs/6.x/notifications). Is not intended to use without it, although you can. You could try to use a library like https://github.com/vitorccs/zenvia-php for this.
